version: '3.3'

services:
  app:
    build: .
    container_name: bot
    restart: always
    ports:
      - "5050:3000"
    volumes:
      - ${HOME}/volumes/bot/logs:/app/logs
    networks:
      - redis_redis-network
    depends_on:
      - redis

  redis:
    image: redis:7.2
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - redis_redis-network

networks:
  redis_redis-network:
    external: true

volumes:
  redis_data: